name: simple_brain_training
description: A new Flutter project.
publish_to: 'none'

version: 1.0.3+4    # 2024/08/28 API34対応

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^1.0.3
  stop_watch_timer:
  cupertino_icons: ^1.0.2
  import_sorter: ^4.6.0
  google_mobile_ads: ^3.1.0
  flutter_localizations:    # 多言語ライブラリの本体
    sdk: flutter  
  intl: 0.19.0           # 多言語やフォーマッタなどの関連ライブラリ
  flutter_launcher_icons: "^0.13.1"


dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_lints: ^2.0.0
  pedantic_mono: any
  # flutter_gen
  build_runner:
  flutter_gen_runner:

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  lineLength: 80   # Optional (default: 80)

  integrations:
    flutter_svg: true


flutter_icons:
  ios: true
  image_path: "assets/icons/app_ios_icon.png"
  remove_alpha_ios: true
  android: true
  adaptive_icon_background: "#FFFBF3"
  adaptive_icon_foreground: "assets/icons/app_android_adaptive_icon_foreground.png"

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/

  fonts:
    - family: ZenKakuGothicNew
      fonts:
      - asset: assets/fonts/ZenKakuGothicNew/ZenKakuGothicNew-Light.ttf
        weight: 300
      - asset: assets/fonts/ZenKakuGothicNew/ZenKakuGothicNew-Medium.ttf
        weight: 400
      - asset: assets/fonts/ZenKakuGothicNew/ZenKakuGothicNew-Regular.ttf
        weight: 500
  